// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/grpcapi/greeter.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestMessage string                 `protobuf:"bytes,1,opt,name=request_message,json=requestMessage,proto3" json:"request_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_internal_grpcapi_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcapi_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcapi_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetRequestMessage() string {
	if x != nil {
		return x.RequestMessage
	}
	return ""
}

type SayHelloResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode    int32                  `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_internal_grpcapi_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcapi_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcapi_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *SayHelloResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

var File_internal_grpcapi_greeter_proto protoreflect.FileDescriptor

const file_internal_grpcapi_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/grpcapi/greeter.proto\x12\agrpcapi\":\n" +
	"\x0fSayHelloRequest\x12'\n" +
	"\x0frequest_message\x18\x01 \x01(\tR\x0erequestMessage\"b\n" +
	"\x10SayHelloResponse\x12#\n" +
	"\rresponse_code\x18\x01 \x01(\x05R\fresponseCode\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage2Q\n" +
	"\x0eGreeterService\x12?\n" +
	"\bSayHello\x12\x18.grpcapi.SayHelloRequest\x1a\x19.grpcapi.SayHelloResponseB%Z#golang-grpc-example/grpcapi;grpcapib\x06proto3"

var (
	file_internal_grpcapi_greeter_proto_rawDescOnce sync.Once
	file_internal_grpcapi_greeter_proto_rawDescData []byte
)

func file_internal_grpcapi_greeter_proto_rawDescGZIP() []byte {
	file_internal_grpcapi_greeter_proto_rawDescOnce.Do(func() {
		file_internal_grpcapi_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpcapi_greeter_proto_rawDesc), len(file_internal_grpcapi_greeter_proto_rawDesc)))
	})
	return file_internal_grpcapi_greeter_proto_rawDescData
}

var file_internal_grpcapi_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpcapi_greeter_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: grpcapi.SayHelloRequest
	(*SayHelloResponse)(nil), // 1: grpcapi.SayHelloResponse
}
var file_internal_grpcapi_greeter_proto_depIdxs = []int32{
	0, // 0: grpcapi.GreeterService.SayHello:input_type -> grpcapi.SayHelloRequest
	1, // 1: grpcapi.GreeterService.SayHello:output_type -> grpcapi.SayHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpcapi_greeter_proto_init() }
func file_internal_grpcapi_greeter_proto_init() {
	if File_internal_grpcapi_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpcapi_greeter_proto_rawDesc), len(file_internal_grpcapi_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcapi_greeter_proto_goTypes,
		DependencyIndexes: file_internal_grpcapi_greeter_proto_depIdxs,
		MessageInfos:      file_internal_grpcapi_greeter_proto_msgTypes,
	}.Build()
	File_internal_grpcapi_greeter_proto = out.File
	file_internal_grpcapi_greeter_proto_goTypes = nil
	file_internal_grpcapi_greeter_proto_depIdxs = nil
}
